# Generated by Django 6.0.1 on 2026-05-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='monthly_qouta',
            new_name='monthly_quota',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='used_qouta',
            new_name='used_quota',
        ),
    ]
